### ISSUE TITLE
GPU Memory Cost

### ISSUE THREAD

**Issue by DingYikang** [danishnazir/SemAttNet#1]
Hi, thanks for your nice work.

How many GPU memory could be cost when `test` and `train` on the KITTI DC dataset?

Looking forward to your reply!

**Comment by danishnazir** [comment]
Hi,
Thank you for your interest in my work.
Please refer to section 4.c (implementation details) here (https://ieeexplore.ieee.org/stamp/stamp.jsp?tp=&arnumber=9918022). If you dont have IEEE account, my paper is also available on Arxiv.
In that section, i discuss in detail about the compute requirements.
