### ISSUE TITLE
Train

### ISSUE THREAD

**Issue by NotHorse0420** [danishnazir/SemAttNet#2]
Hi @danishnazir 
It's a really great work, I'd like to know how can I train it? Thank you.

**Comment by danishnazir** [comment]
Hi, 
Thank you for your interest in my work.
Please follow this link ( https://github.com/danishnazir/SemAttNet/tree/training ) for detailed training instructions.

**Comment by NotHorse0420** [comment]
> Hi, Thank you for your interest in my work. Please follow this link ( https://github.com/danishnazir/SemAttNet/tree/training ) for detailed training instructions.

Thank you very much for your reply.
