### ISSUE TITLE
Unable to create conda env using req.txt

### ISSUE THREAD

**Issue by hardik01shah** [danishnazir/SemAttNet#3]
Hi @danishnazir !
This is really interesting work.

I have been facing issues creating a conda env using 
`conda create -n <environment-name> --file req.txt`.
I get a 'packages not found error'. From this [issue](https://stackoverflow.com/questions/70774618/conda-create-from-requirements-txt-not-finding-packages) it looks like you had some packages installed via pip and when you exported the env to a .txt the _pypi_0 prefix is added which is not understood when creating a new env.

I think exporting to a .yaml file should resolve this. Would be great if you can look into it.
Thanks!

**Comment by danishnazir** [comment]
HI @hardik01shah 

Thank you for your interest. I dont have access to the environment now, so unfortunately, I cannot create the yml file. However, one quick work around (not so clean) is as follows.
`conda create -n <environment-name> `
`conda activate  <environment-name> ` 
`pip install -r  req.txt ` 

Other solutions includes removing all such references and installing them one by one using conda.

Regards,
