### ISSUE TITLE
RMSE maintained around 7000 and do not decrease

### ISSUE THREAD

**Issue by SilverRAN** [danishnazir/SemAttNet#4]
Hi! Thank you very much for your outstanding research! I have a question: when I want to train a model from the beginning, the RMSE of three-branch backbone decreased from around 10000 to 7000 during the first 5 epoches, but then the RMSE didn't continue to decrease. It seems to converged at 7000 RMSE, which is 10 times larger than the expected RMSE you mentioned. All of the parameters are set to default. I wonder what the reason could be. Thanks a lot if you can answer my question!

**Comment by danishnazir** [comment]
Hi,
Thank you for your interest.
Do you mean the RMSE on train or val set? and What exactly do you mean by "10 times larger" ? 
Thanks,

**Comment by SilverRAN** [comment]
> Hi, Thank you for your interest. Do you mean the RMSE on train or val set? and What exactly do you mean by "10 times larger" ? Thanks,

Thanks for your reply! In fact I found I'm loading the data in a wrong way, which made the RGB data not correspond to the depth map. The problem was already solved. You can conclude this issue.
